package com.aura.memory.onnx

/**
 * BERT WordPiece tokenization, matching HuggingFace's `BertTokenizer` exactly.
 *
 * Exactness is the whole requirement, and it is the requirement because getting it wrong
 * is invisible. A tokenizer that splits a contraction differently, or keeps an accent the
 * reference strips, still returns a well-formed sequence; the model still returns a
 * well-formed vector of the right length; nothing errors. The embedding is simply of text
 * the model was never shown, and recall gets quietly worse for a reason no log explains.
 *
 * So this is not written from the paper. `WordPieceTokenizerTest` asserts equality against
 * ids generated by the real `BertTokenizer` for `nomic-ai/nomic-embed-text-v1.5`, and that
 * fixture is the specification.
 *
 * The steps, in the order the reference applies them:
 *   1. drop control characters, normalise whitespace
 *   2. pad CJK characters so each becomes its own token
 *   3. lowercase and strip accents — `do_lower_case: true` implies both
 *   4. split on whitespace, then split punctuation into standalone tokens
 *   5. greedy longest-match-first WordPiece per word, `##` marking continuations
 *
 * @param vocabLines `vocab.txt`, one token per line, index = id.
 */
class WordPieceTokenizer(vocabLines: List<String>) {

    private val vocab: Map<String, Int> =
        vocabLines.asSequence()
            .mapIndexed { index, token -> token.trim() to index }
            .filter { it.first.isNotEmpty() }
            .toMap()

    val vocabSize: Int get() = vocab.size
    val clsId: Int = id("[CLS]")
    val sepId: Int = id("[SEP]")
    val padId: Int = id("[PAD]")
    val unkId: Int = id("[UNK]")

    private fun id(token: String): Int =
        vocab[token] ?: error("vocabulary is missing the required token $token")

    /**
     * Encode [text] to token ids, wrapped in `[CLS]` and `[SEP]`.
     *
     * Truncation keeps both markers: a sequence missing its opening or closing token is
     * not the shape the model was trained on, and a long memory that silently failed to
     * embed would be unretrievable with nothing to show for it.
     */
    fun encode(text: String, maxTokens: Int = MAX_TOKENS): List<Int> {
        require(maxTokens >= 2) { "maxTokens must leave room for [CLS] and [SEP]" }
        val body = tokenize(text).map { vocab[it] ?: unkId }
        val room = maxTokens - 2
        val out = ArrayList<Int>(minOf(body.size, room) + 2)
        out.add(clsId)
        out.addAll(if (body.size > room) body.subList(0, room) else body)
        out.add(sepId)
        return out
    }

    /** The word pieces for [text], without the special tokens. Exposed for testing. */
    fun tokenize(text: String): List<String> =
        basicTokenize(text).flatMap { wordPieces(it) }

    // ── step 1-4: the "basic" tokenizer ──────────────────────────────────────

    private fun basicTokenize(text: String): List<String> {
        // By code point, not by Char. Kotlin stores anything above the BMP as a surrogate
        // pair, and Character.getType calls each half a SURROGATE — so a Char-wise loop
        // classifies every emoji as a control character and deletes it. The reference keeps
        // it and lets WordPiece resolve it to [UNK]. That difference is not cosmetic: a
        // memory containing an emoji would embed as though the emoji were not there.
        val cleaned = buildString(text.length) {
            var i = 0
            while (i < text.length) {
                val cp = text.codePointAt(i)
                // 0xFFFD is the replacement character: the reference drops it along with
                // the control range rather than embedding a decoding failure.
                when {
                    cp == 0 || cp == 0xFFFD || isControl(cp) -> Unit
                    Character.isWhitespace(cp) -> append(' ')
                    // Padded so each ideograph tokenizes alone, as the reference does.
                    isCjk(cp) -> append(' ').appendCodePoint(cp).append(' ')
                    else -> appendCodePoint(cp)
                }
                i += Character.charCount(cp)
            }
        }
        return cleaned.split(' ')
            .asSequence()
            .filter { it.isNotEmpty() }
            .map { stripAccents(it.lowercase()) }
            .flatMap { splitOnPunctuation(it) }
            .filter { it.isNotEmpty() }
            .toList()
    }

    /**
     * NFD-decompose and drop combining marks, so `café` becomes `cafe`.
     *
     * `do_lower_case: true` turns this on in the reference, which is easy to miss because
     * nothing in the config says "strip_accents".
     */
    private fun stripAccents(text: String): String {
        val decomposed = java.text.Normalizer.normalize(text, java.text.Normalizer.Form.NFD)
        return buildString(decomposed.length) {
            for (ch in decomposed) {
                if (Character.getType(ch) != Character.NON_SPACING_MARK.toInt()) append(ch)
            }
        }
    }

    /** Punctuation becomes its own token rather than clinging to the word beside it. */
    private fun splitOnPunctuation(word: String): List<String> {
        if (word.isEmpty()) return emptyList()
        val out = mutableListOf<String>()
        val current = StringBuilder()
        for (ch in word) {
            if (isPunctuation(ch)) {
                if (current.isNotEmpty()) {
                    out.add(current.toString())
                    current.clear()
                }
                out.add(ch.toString())
            } else {
                current.append(ch)
            }
        }
        if (current.isNotEmpty()) out.add(current.toString())
        return out
    }

    // ── step 5: WordPiece ────────────────────────────────────────────────────

    /**
     * Greedy longest-match-first, `##` on every piece after the first.
     *
     * A word longer than [MAX_WORD_CHARS] goes straight to `[UNK]` rather than being
     * chewed through character by character — that is the reference's behaviour, and the
     * pathological input it protects against is a base64 blob pasted into a memory.
     */
    private fun wordPieces(word: String): List<String> {
        if (word.length > MAX_WORD_CHARS) return listOf("[UNK]")
        val pieces = mutableListOf<String>()
        var start = 0
        while (start < word.length) {
            var end = word.length
            var found: String? = null
            while (start < end) {
                val piece = if (start == 0) word.substring(start, end) else "##" + word.substring(start, end)
                if (piece in vocab) {
                    found = piece
                    break
                }
                end--
            }
            // One unmatchable piece makes the WHOLE word unknown, not just that piece.
            // Emitting the prefix that did match would hand the model a fragment it never
            // saw in training as a standalone token.
            if (found == null) return listOf("[UNK]")
            pieces.add(found)
            start = end
        }
        return pieces
    }

    // ── character classes, matching the reference's definitions ──────────────

    private fun isControl(cp: Int): Boolean {
        if (cp == '\t'.code || cp == '\n'.code || cp == '\r'.code) return false
        return when (Character.getType(cp).toByte()) {
            // SURROGATE is deliberately absent. Iterating by code point means a lone
            // surrogate cannot reach here, and treating one as a control character is
            // exactly how every emoji was being silently deleted instead of becoming [UNK].
            Character.CONTROL, Character.FORMAT,
            Character.PRIVATE_USE, Character.UNASSIGNED,
            -> true
            else -> false
        }
    }

    /**
     * ASCII punctuation plus anything Unicode calls punctuation.
     *
     * The ASCII ranges are listed explicitly because the reference does: characters like
     * `$`, `+`, `<` and `^` are Symbol rather than Punctuation to Unicode, and the
     * reference still splits on them.
     */
    private fun isPunctuation(ch: Char): Boolean {
        val cp = ch.code
        if (cp in 33..47 || cp in 58..64 || cp in 91..96 || cp in 123..126) return true
        return when (Character.getType(ch).toByte()) {
            Character.CONNECTOR_PUNCTUATION, Character.DASH_PUNCTUATION,
            Character.START_PUNCTUATION, Character.END_PUNCTUATION,
            Character.INITIAL_QUOTE_PUNCTUATION, Character.FINAL_QUOTE_PUNCTUATION,
            Character.OTHER_PUNCTUATION,
            -> true
            else -> false
        }
    }

    private fun isCjk(cp: Int): Boolean =
        cp in 0x4E00..0x9FFF || cp in 0x3400..0x4DBF || cp in 0x20000..0x2A6DF ||
            cp in 0x2A700..0x2B73F || cp in 0x2B740..0x2B81F || cp in 0x2B820..0x2CEAF ||
            cp in 0xF900..0xFAFF || cp in 0x2F800..0x2FA1F

    companion object {
        /**
         * Tokens per embedding call.
         *
         * nomic-embed-text-v1.5 accepts 8192, but a memory is a sentence or two and the
         * cost of a forward pass grows with the square of the sequence. 512 covers any
         * realistic memory with room to spare and keeps a single embed in the tens of
         * milliseconds rather than the hundreds.
         */
        const val MAX_TOKENS = 512

        /** Beyond this a "word" is a blob, not language. Matches the reference. */
        const val MAX_WORD_CHARS = 100
    }
}
