package com.aura.dream

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * A proposed new KG edge between two existing knowledge graph nodes.
 *
 * Generated by [DreamConsolidator.densifyGraph] using Jaccard
 * similarity on the node labels. The Python implementation only
 * logs these as graph_proposals in the cycle report and doesn't
 * persist them; on Android we persist them so the user can review
 * and accept/reject them in the DreamSummaries UI.
 *
 * Status transitions:
 *   PENDING -> ACCEPTED (user accepts, edge inserted into KG)
 *   PENDING -> REJECTED (user dismisses, edge never inserted)
 *   PENDING -> EXPIRED  (auto-aged after 30 days, user didn't act)
 */
@Entity(
    tableName = "kg_edge_proposals",
    indices = [
        Index("status"),
        Index("similarity"),
        // Pair is unique so the same (fromNodeId, toNodeId) doesn't
        // re-appear cycle after cycle. The user sees it once.
        Index(value = ["fromNodeId", "toNodeId"], unique = true),
    ],
)
data class KgEdgeProposalEntity(
    @PrimaryKey val id: String,                 // "proposal_<from>_<to>"
    val fromNodeId: String,
    val toNodeId: String,
    val fromLabel: String,
    val toLabel: String,
    /** Jaccard similarity on the labels' tokens. 0.0-1.0. */
    val similarity: Float,
    /** Type of edge proposed. Always RELATES_TO in v1; reserved for future. */
    val proposedEdge: String = "RELATES_TO",
    val status: String = "PENDING",             // PENDING | ACCEPTED | REJECTED | EXPIRED
    val createdAt: Long = System.currentTimeMillis(),
    val decidedAt: Long? = null,
)
