"""
Tool: count_words
Description: Count the number of words in a given text
Auto-generated by SynapseForge on 2026-01-30T15:06:26.310941
"""

def execute(text: str) -> dict:
    """
    Count the number of words in a given text

    Returns:
        dict with 'success' (bool) and 'result' (any) keys
    """
    try:
        result = len(text.split())
        return {"success": True, "result": result}
    except Exception as e:
        return {"success": False, "error": str(e)}


# Test
if __name__ == "__main__":
    test_result = execute(text='This is a test.')
    print(f"Test result: {test_result}")
    assert test_result.get("success"), f"Test failed: {test_result}"
