"""
Tool: is_prime
Description: Check if a number is prime
Auto-generated by SynapseForge on 2026-01-30T15:23:14.457235
"""

def execute(num: int) -> dict:
    """
    Check if a number is prime

    Returns:
        dict with 'success' (bool) and 'result' (any) keys
    """
    try:
        result = all(num % i > 0 for i in range(2, int(num ** 0.5) + 1))
        return {"success": True, "result": result}
    except Exception as e:
        return {"success": False, "error": str(e)}


# Test
if __name__ == "__main__":
    test_result = execute(num=7)
    print(f"Test result: {test_result}")
    assert test_result.get("success"), f"Test failed: {test_result}"
