"""
Tool: word_frequency
Description: Counts the frequency of each word in a given text
Auto-generated by SynapseForge on 2026-01-30T17:43:45.528025
"""

def execute(text: str) -> dict:
    """
    Counts the frequency of each word in a given text

    Returns:
        dict with 'success' (bool) and 'result' (any) keys
    """
    try:
        result = {}
        for word in text.split():
        	if word not in result:
        		result[word] = 1
        	else:
        		result[word] += 1
        return {"success": True, "result": result}
    except Exception as e:
        return {"success": False, "error": str(e)}


# Test
if __name__ == "__main__":
    test_result = execute(text='the quick brown fox jumps over the lazy dog')
    print(f"Test result: {test_result}")
    assert test_result.get("success"), f"Test failed: {test_result}"
