package com.aura.skills

import com.aura.security.SecureDataStore
import io.mockk.coEvery
import io.mockk.mockk
import kotlinx.coroutines.test.runTest
import org.junit.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * The skills Aura arrives with.
 *
 * Until now the only ones that shipped were creative-writing craft prompts, generated by
 * `CraftSkills.seeds()` from the writing templates and read back by `CraftResolver` inside
 * the creative engine. Nothing general-purpose existed, so a fresh install's skill list was
 * empty for every purpose except drafting fiction — and a feature whose list is empty is a
 * feature nobody discovers.
 *
 * The seeding mechanism itself was already right: [SkillsStore.seedBuiltins] keys on absent
 * *names*, so it is safe on every startup, adds only what a later version introduced, and
 * leaves an author's rewrite alone forever. This is content arriving through a door that
 * was already built.
 */
class BuiltinSkillsTest {

    private fun newStore(initial: Map<String, String?> = emptyMap()): SkillsStore {
        val secure = mockk<SecureDataStore>(relaxed = true)
        coEvery { secure.getString(any()) } answers { firstArg<String>().let { initial[it] } }
        coEvery { secure.putString(any(), any()) } returns Unit
        return SkillsStore(secure)
    }

    @Test
    fun `every seed is usable as it ships`() {
        val seeds = BuiltinSkills.seeds()

        assertTrue(seeds.size >= 10, "only ${seeds.size} builtin skills — the list is the feature")
        seeds.forEach { skill ->
            assertTrue(skill.builtin, "${skill.name} is not marked builtin, so resetBuiltin cannot restore it")
            assertTrue(skill.name.isNotBlank(), "a skill with no name cannot be invoked")
            assertTrue(skill.description.isNotBlank(), "${skill.name} has no description, so list_skills cannot explain it")
            assertTrue(
                skill.body.length > 200,
                "${skill.name}'s body is ${skill.body.length} chars — too short to be a procedure worth following",
            )
        }
    }

    @Test
    fun `names are unique and lookup-safe`() {
        // seedBuiltins and findByName both key on lowercased names. Two seeds differing
        // only in case would make one of them permanently unreachable.
        val names = BuiltinSkills.seeds().map { it.name.lowercase() }

        assertEquals(names.size, names.toSet().size, "duplicate builtin skill name: $names")
        names.forEach { assertTrue(it == it.trim(), "'$it' has surrounding whitespace") }
    }

    @Test
    fun `seeding a fresh install installs all of them`() = runTest {
        val store = newStore()

        store.seedBuiltins(BuiltinSkills.seeds())

        assertEquals(BuiltinSkills.seeds().size, store.skills.value.size)
        BuiltinSkills.seeds().forEach { seed ->
            assertTrue(store.findByName(seed.name) != null, "${seed.name} did not survive seeding")
        }
    }

    @Test
    fun `re-seeding leaves a rewritten skill alone`() = runTest {
        // The property that makes seeding safe on every startup. If this breaks, every
        // launch silently reverts whatever the user changed.
        val store = newStore()
        store.seedBuiltins(BuiltinSkills.seeds())
        val mine = store.findByName(BuiltinSkills.seeds().first().name)!!
        store.update(mine.withBody("my own version"))

        store.seedBuiltins(BuiltinSkills.seeds())

        assertEquals("my own version", store.findByName(mine.name)!!.body)
        assertEquals(BuiltinSkills.seeds().size, store.skills.value.size, "re-seeding duplicated a skill")
    }

    @Test
    fun `the craft skills and the general ones can coexist`() = runTest {
        // Both are seeded from ProactiveBootstrap on the same startup. They share a
        // namespace, so a name collision would silently drop one of the two.
        val craft = com.aura.creative.CraftSkills.seeds().map { it.name.lowercase() }.toSet()
        val general = BuiltinSkills.seeds().map { it.name.lowercase() }.toSet()

        assertTrue(
            craft.intersect(general).isEmpty(),
            "name collision between craft and general skills: ${craft.intersect(general)}",
        )
    }
}
