"""Auto-generated custom tool: bmi_calculator

Description: Calculate Body Mass Index (BMI) from height and weight
Created: 2026-01-18T18:34:03.961262
Status: pending

WARNING: This file was auto-generated by ToolBuilderTool.
Do not edit manually unless you know what you're doing.
"""

import re
from typing import Any



class BmiCalculatorTool:
    """Calculate Body Mass Index (BMI) from height and weight"""

    def __init__(self):
        self.name = "bmi_calculator"
        self.description = "Calculate Body Mass Index (BMI) from height and weight"

    def calculate_bmi(self, weight_kg: Any, height_m: Any) -> dict:
        """Calculate BMI from weight in kg and height in meters

        Args:
            weight_kg: Parameter weight_kg
            height_m: Parameter height_m

        Returns:
            Result dictionary with success status and data
        """
        try:
            weight = float(weight_kg)
            height = float(height_m)
            bmi = weight / (height ** 2)
            category = 'Underweight' if bmi < 18.5 else 'Normal' if bmi < 25 else 'Overweight' if bmi < 30 else 'Obese'
            return {"success": True, "bmi": round(bmi, 1), "category": category}
        except Exception as e:
            return {"success": False, "error": str(e)}

    def calculate_bmi_imperial(self, weight_lbs: Any, height_inches: Any) -> dict:
        """Calculate BMI from weight in pounds and height in inches

        Args:
            weight_lbs: Parameter weight_lbs
            height_inches: Parameter height_inches

        Returns:
            Result dictionary with success status and data
        """
        try:
            weight = float(weight_lbs)
            height = float(height_inches)
            bmi = (weight * 703) / (height ** 2)
            category = 'Underweight' if bmi < 18.5 else 'Normal' if bmi < 25 else 'Overweight' if bmi < 30 else 'Obese'
            return {"success": True, "bmi": round(bmi, 1), "category": category}
        except Exception as e:
            return {"success": False, "error": str(e)}


    def _extract_param(self, action: str, param_name: str, index: int) -> Any:
        """Extract a parameter from the action string."""
        # Try to find named parameter
        pattern = rf'{param_name}[=:]\s*["\'"]?([^"\'"\s]+)["\'"]?'
        match = re.search(pattern, action, re.IGNORECASE)
        if match:
            return match.group(1)
        # Try to extract by position from quoted strings
        quoted = re.findall(r'["\'"]([^"\'"]+)["\'"]', action)
        if index < len(quoted):
            return quoted[index]
        # Try to extract numbers
        numbers = re.findall(r'\b\d+(?:\.\d+)?\b', action)
        if index < len(numbers):
            return numbers[index]
        return None


    def execute(self, action: str) -> dict:
        """Execute an action on this tool.

        Args:
            action: The action string to parse and execute

        Returns:
            Result dictionary with success status and data
        """
        action_lower = action.lower()

        # Check for explicit function names first
        if "calculate_bmi_imperial" in action_lower:
            weight_lbs = self._extract_param(action, "weight_lbs", 0)
            height_inches = self._extract_param(action, "height_inches", 1)
            return self.calculate_bmi_imperial(weight_lbs, height_inches)

        if "calculate_bmi" in action_lower:
            weight_kg = self._extract_param(action, "weight_kg", 0)
            height_m = self._extract_param(action, "height_m", 1)
            return self.calculate_bmi(weight_kg, height_m)

        # Natural language parsing for BMI queries
        if "bmi" in action_lower or "body mass" in action_lower:
            # Check if imperial units are mentioned
            is_imperial = any(unit in action_lower for unit in ['lb', 'lbs', 'pound', 'feet', 'foot', 'inch', 'inches', "'", '"'])

            # Extract height and weight from natural language
            weight = None
            height = None

            # Look for patterns like "weight 70kg" or "70kg" or "70 kg"
            weight_patterns = [
                r'weight[:\s]+(\d+(?:\.\d+)?)\s*(?:kg|kilogram)?',
                r'(\d+(?:\.\d+)?)\s*(?:kg|kilogram)',
                r'(\d+(?:\.\d+)?)\s*(?:lb|lbs|pound)',
            ]
            for pattern in weight_patterns:
                match = re.search(pattern, action_lower)
                if match:
                    weight = float(match.group(1))
                    break

            # Look for patterns like "height 1.75m" or "1.75m" or "175cm"
            height_patterns = [
                (r'height[:\s]+(\d+(?:\.\d+)?)\s*(?:m|meter|metre)?', 'metric'),
                (r'(\d+(?:\.\d+)?)\s*(?:m|meter|metre)(?:\s|,|$)', 'metric'),
                (r'(\d+)\s*(?:cm|centimeter)', 'cm'),
                (r'(\d+(?:\.\d+)?)\s*(?:inch|inches|in\b)', 'inches'),
                (r'(\d+(?:\.\d+)?)\s*(?:feet|foot|ft)', 'feet'),
                (r"(\d+)'(\d+)\"?", 'feet_inches'),  # 5'10" format
            ]
            for pattern, unit_type in height_patterns:
                match = re.search(pattern, action_lower)
                if match:
                    if unit_type == 'cm':
                        height = float(match.group(1)) / 100  # Convert cm to m
                    elif unit_type == 'inches':
                        height = float(match.group(1))  # Already in inches
                        is_imperial = True
                    elif unit_type == 'feet':
                        height = float(match.group(1)) * 12  # Convert to inches for imperial
                        is_imperial = True
                    elif unit_type == 'feet_inches':
                        feet = int(match.group(1))
                        inches = int(match.group(2)) if match.group(2) else 0
                        height = feet * 12 + inches  # Total inches
                        is_imperial = True
                    else:  # metric
                        height = float(match.group(1))
                    break

            # If we couldn't find labeled values, try extracting numbers in order
            if weight is None or height is None:
                numbers = re.findall(r'\b(\d+(?:\.\d+)?)\b', action)
                numbers = [float(n) for n in numbers]
                if len(numbers) >= 2:
                    # Heuristic: larger number is usually weight, smaller is height
                    # Unless height is in cm (> 100)
                    if numbers[0] > 100:  # Likely cm
                        height = numbers[0] / 100
                        weight = numbers[1] if len(numbers) > 1 else None
                    elif numbers[1] > 100:  # Second number is cm
                        height = numbers[1] / 100
                        weight = numbers[0]
                    elif numbers[0] > numbers[1]:
                        weight = numbers[0]
                        height = numbers[1]
                    else:
                        weight = numbers[1]
                        height = numbers[0]

            if weight is not None and height is not None:
                if is_imperial:
                    return self.calculate_bmi_imperial(weight, height)
                else:
                    return self.calculate_bmi(weight, height)

            return {"success": False, "error": "Could not extract weight and height from input. Please provide weight (kg) and height (m)."}

        return {"success": False, "error": f"Unknown action: {action}"}
