"""
SynapseForge - Dynamic Tool Creation for AURA

Creates NEW tools at runtime when capability gaps are detected.
Tools are generated as Python code, validated in a sandbox, and stored for future use.

Flow:
    Capability Gap Detected -> Generate Tool Code -> Validate in Sandbox -> Store Tool -> Use It
"""

import json
import logging
import os as _os
import re
import subprocess
import sys
import tempfile
import ast as _ast
from dataclasses import dataclass, asdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import requests

from ..config import Config
from .tool_contract import ToolResult

_SAFE_ENV = {
    'PATH': _os.environ.get('PATH', ''),
    'SYSTEMROOT': _os.environ.get('SYSTEMROOT', ''),
    'TEMP': _os.environ.get('TEMP', ''),
    'TMP': _os.environ.get('TMP', ''),
}

logger = logging.getLogger(__name__)

_SF_BLOCKED_BUILTINS = {"eval", "exec", "compile", "__import__", "open", "breakpoint"}
_SF_BLOCKED_MODULES = {"subprocess", "os", "sys", "shutil", "socket", "ctypes", "importlib", "pickle", "builtins", "__builtins__", "requests", "httpx", "urllib", "urllib3", "aiohttp", "http"}


def _scan_for_dangerous_code(code: str) -> tuple:
    """AST-based safety check for generated code."""
    try:
        tree = _ast.parse(code)
    except SyntaxError as e:
        return True, f"Syntax error: {e}"
    for node in _ast.walk(tree):
        if isinstance(node, _ast.Call):
            if isinstance(node.func, _ast.Name) and node.func.id in _SF_BLOCKED_BUILTINS:
                return True, f"Blocked builtin: {node.func.id}"
            if isinstance(node.func, _ast.Attribute) and node.func.attr in _SF_BLOCKED_BUILTINS:
                return True, f"Blocked builtin: {node.func.attr}"
        if isinstance(node, (_ast.Import, _ast.ImportFrom)):
            names = [a.name for a in node.names] if isinstance(node, _ast.Import) else [node.module or ""]
            for name in names:
                if name and name.split(".")[0] in _SF_BLOCKED_MODULES:
                    return True, f"Blocked module: {name}"
    return False, ""


@dataclass
class SynthesizedTool:
    """A tool that was dynamically created by SynapseForge."""
    name: str              # Tool name (snake_case)
    description: str       # What it does
    code: str              # Full Python code
    created_at: str        # Timestamp
    test_passed: bool      # Validation result
    usage_count: int       # Times used


class SynapseForge:
    """
    Dynamic tool synthesizer that creates new capabilities on demand.

    Example:
        forge = SynapseForge()
        tool = forge.synthesize("convert celsius to fahrenheit")
        result = forge.execute_tool(tool.name, celsius=100)
    """

    TOOL_TEMPLATE = '''"""
Tool: {name}
Description: {description}
Auto-generated by SynapseForge on {timestamp}
"""

def execute({parameters}) -> dict:
    """
    {description}

    Returns:
        dict with 'success' (bool) and 'result' (any) keys
    """
    try:
{code_body}
        return {{"success": True, "result": result}}
    except Exception as e:
        return {{"success": False, "error": str(e)}}


# Test
if __name__ == "__main__":
    test_result = execute({test_args})
    print(f"Test result: {{test_result}}")
    assert test_result.get("success"), f"Test failed: {{test_result}}"
'''

    SPEC_PROMPT = '''You must return ONLY a JSON object, no other text or code.

CAPABILITY NEEDED: {capability_request}

Return this exact JSON structure (fill in the values):
{{
    "name": "snake_case_name",
    "description": "what the tool does",
    "parameters": "param_name: type",
    "code_body": "python code using result variable",
    "test_args": "param_name=test_value"
}}

Rules for code_body:
- Store final output in variable called 'result'
- Use standard library only
- Use \\n for newlines in code

Example response for "convert miles to kilometers":
{{
    "name": "miles_to_km",
    "description": "Convert miles to kilometers",
    "parameters": "miles: float",
    "code_body": "result = miles * 1.60934",
    "test_args": "miles=10.0"
}}

Now return JSON for: {capability_request}
JSON:'''

    FIX_PROMPT = '''The following Python code has an error:

CODE:
```python
{code}
```

ERROR:
{error}

Fix the code and return ONLY the complete fixed Python code, nothing else.
Keep the same structure with execute() function and test block.

Fixed code:'''

    def __init__(
        self,
        ollama_url: str = None,
        model: str = None,
        tools_dir: Optional[str] = None,
        registry_path: Optional[str] = None
    ):
        """
        Initialize SynapseForge.

        Args:
            ollama_url: URL for Ollama API (defaults to Config.OLLAMA_HOST)
            model: Model to use for code generation (defaults to Config.MODEL_CODE)
            tools_dir: Directory to store synthesized tool files
            registry_path: Path to registry JSON file
        """
        self.ollama_url = (ollama_url or Config.OLLAMA_HOST).rstrip("/")
        self.model = model or Config.MODEL_CODE  # Use code-specialized model

        # Set up paths
        base_dir = Path(__file__).parent

        if tools_dir is None:
            self.tools_dir = base_dir / "synthesized"
        else:
            self.tools_dir = Path(tools_dir)
        self.tools_dir.mkdir(parents=True, exist_ok=True)

        if registry_path is None:
            # Go up to project root -> data/synapseforge
            data_dir = base_dir.parent.parent / "data" / "synapseforge"
            data_dir.mkdir(parents=True, exist_ok=True)
            self.registry_path = data_dir / "registry.json"
        else:
            self.registry_path = Path(registry_path)
            self.registry_path.parent.mkdir(parents=True, exist_ok=True)

        # Load existing registry
        self.registry: Dict[str, SynthesizedTool] = self._load_registry()

        logger.info(f"SynapseForge initialized with {len(self.registry)} tools")

    def _load_registry(self) -> Dict[str, SynthesizedTool]:
        """Load tool registry from JSON file."""
        registry = {}

        if not self.registry_path.exists():
            # Create empty registry
            self._save_registry_data({})
            return registry

        try:
            with open(self.registry_path, "r", encoding="utf-8") as f:
                data = json.load(f)

            for name, tool_data in data.items():
                registry[name] = SynthesizedTool(**tool_data)

        except (json.JSONDecodeError, IOError) as e:
            logger.warning(f"Failed to load registry, starting fresh: {e}")
            self._save_registry_data({})

        return registry

    def _save_registry(self) -> None:
        """Save registry to JSON file."""
        data = {name: asdict(tool) for name, tool in self.registry.items()}
        self._save_registry_data(data)

    def _save_registry_data(self, data: dict) -> None:
        """Write registry data to file."""
        try:
            with open(self.registry_path, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=2)
        except IOError as e:
            logger.error(f"Failed to save registry: {e}")

    def _call_llm(self, prompt: str, timeout: int = 90) -> str:
        """Call Ollama API for code generation."""
        try:
            response = requests.post(
                f"{self.ollama_url}/api/generate",
                json={
                    "model": self.model,
                    "prompt": prompt,
                    "stream": False,
                    "options": {
                        "temperature": 0.3,  # Low temp for code
                        "num_predict": 2048
                    }
                },
                timeout=timeout
            )
            response.raise_for_status()
            return response.json().get("response", "").strip()
        except requests.exceptions.Timeout:
            logger.warning("LLM request timed out")
            return ""
        except requests.exceptions.RequestException as e:
            logger.error(f"LLM request failed: {e}")
            return ""

    def _extract_json(self, text: str) -> Optional[dict]:
        """Extract JSON object from LLM response."""
        # Try direct parse first
        text = text.strip()
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            pass

        # Try to find JSON in code block
        json_match = re.search(r'```(?:json)?\s*(\{.*?\})\s*```', text, re.DOTALL)
        if json_match:
            try:
                return json.loads(json_match.group(1))
            except json.JSONDecodeError:
                pass

        # Find the first { and matching }
        start = text.find('{')
        if start != -1:
            # Count braces to find matching close
            depth = 0
            for i, char in enumerate(text[start:], start):
                if char == '{':
                    depth += 1
                elif char == '}':
                    depth -= 1
                    if depth == 0:
                        try:
                            return json.loads(text[start:i + 1])
                        except json.JSONDecodeError:
                            break

        # Try to extract fields manually if JSON parsing fails
        name_match = re.search(r'"name"\s*:\s*"([^"]+)"', text)
        desc_match = re.search(r'"description"\s*:\s*"([^"]+)"', text)
        params_match = re.search(r'"parameters"\s*:\s*"([^"]+)"', text)
        code_match = re.search(r'"code_body"\s*:\s*"([^"]*(?:\\.[^"]*)*)"', text)
        test_match = re.search(r'"test_args"\s*:\s*"([^"]+)"', text)

        if name_match and desc_match and params_match and code_match and test_match:
            return {
                "name": name_match.group(1),
                "description": desc_match.group(1),
                "parameters": params_match.group(1),
                "code_body": code_match.group(1).replace('\\n', '\n'),
                "test_args": test_match.group(1)
            }

        return None

    def _generate_spec(self, capability_request: str) -> Optional[dict]:
        """Generate tool specification via LLM."""
        prompt = self.SPEC_PROMPT.format(capability_request=capability_request)
        response = self._call_llm(prompt)

        if not response:
            logger.error("Failed to generate tool spec: empty response")
            return None

        spec = self._extract_json(response)

        if not spec:
            logger.error(f"Failed to parse tool spec from response: {response[:200]}")
            return None

        # Validate required fields
        required = ["name", "description", "parameters", "code_body", "test_args"]
        for field in required:
            if field not in spec:
                logger.error(f"Missing required field '{field}' in spec")
                return None

        # Sanitize name
        spec["name"] = re.sub(r'[^a-z0-9_]', '_', spec["name"].lower())

        return spec

    def _build_tool_code(self, spec: dict) -> str:
        """Build full tool code from specification."""
        # Ensure code_body is properly indented (8 spaces)
        code_lines = spec["code_body"].split("\n")
        indented_code = "\n".join(
            "        " + line if line.strip() else line
            for line in code_lines
        )

        return self.TOOL_TEMPLATE.format(
            name=spec["name"],
            description=spec["description"],
            timestamp=datetime.now().isoformat(),
            parameters=spec["parameters"],
            code_body=indented_code,
            test_args=spec["test_args"]
        )

    def _validate_code(self, code: str) -> tuple:
        """Run code in subprocess to validate it works."""
        dangerous, reason = _scan_for_dangerous_code(code)
        if dangerous:
            return False, f"Generated code failed safety check: {reason}"

        with tempfile.NamedTemporaryFile(
            mode='w',
            suffix='.py',
            delete=False,
            encoding='utf-8'
        ) as f:
            f.write(code)
            f.flush()
            temp_path = Path(f.name)

        try:
            result = subprocess.run(
                [sys.executable, str(temp_path)],
                capture_output=True,
                text=True,
                timeout=10,  # Kill if takes too long
                cwd=tempfile.gettempdir(),  # Isolate working directory
                env=_SAFE_ENV,
            )

            if result.returncode == 0:
                return True, result.stdout
            else:
                return False, result.stderr
        except subprocess.TimeoutExpired:
            return False, "Execution timed out (10s limit)"
        except Exception as e:
            return False, f"Execution error: {str(e)}"
        finally:
            temp_path.unlink(missing_ok=True)

    def _fix_code(self, code: str, error: str) -> str:
        """Attempt to fix broken code via LLM."""
        prompt = self.FIX_PROMPT.format(code=code, error=error)
        response = self._call_llm(prompt)

        if not response:
            return code

        # Extract code from response
        code_match = re.search(r'```python\s*(.*?)```', response, re.DOTALL)
        if code_match:
            return code_match.group(1).strip()

        # If no code block, check if response looks like code
        if "def execute(" in response:
            return response.strip()

        return code

    def _save_tool_file(self, tool: SynthesizedTool) -> None:
        """Save tool code to file."""
        tool_path = self.tools_dir / f"{tool.name}.py"
        try:
            with open(tool_path, "w", encoding="utf-8") as f:
                f.write(tool.code)
            logger.info(f"Saved tool to {tool_path}")
        except IOError as e:
            logger.error(f"Failed to save tool file: {e}")

    def find_tool(self, capability: str) -> Optional[SynthesizedTool]:
        """
        Find existing tool that matches capability.

        Uses simple keyword matching against tool names and descriptions.

        Args:
            capability: Description of needed capability

        Returns:
            Matching tool or None
        """
        capability_words = set(capability.lower().split())

        # Remove common words
        stop_words = {"a", "an", "the", "to", "from", "for", "in", "on", "with", "and", "or"}
        capability_words -= stop_words

        best_match = None
        best_score = 0

        for name, tool in self.registry.items():
            if not tool.test_passed:
                continue  # Skip broken tools

            # Check name
            name_words = set(name.split('_'))
            name_score = len(capability_words & name_words)

            # Check description
            desc_words = set(tool.description.lower().split()) - stop_words
            desc_score = len(capability_words & desc_words)

            total_score = name_score * 2 + desc_score  # Weight name matches higher

            if total_score > best_score:
                best_score = total_score
                best_match = tool

        # Require at least some match
        if best_score >= 2:
            return best_match

        return None

    def synthesize(self, capability_request: str) -> Optional[SynthesizedTool]:
        """
        Generate a new tool for the requested capability.

        Args:
            capability_request: Description of what the tool should do

        Returns:
            SynthesizedTool if successful, None if failed
        """
        logger.info(f"Synthesizing tool for: {capability_request}")

        # 1. Check if tool already exists
        existing = self.find_tool(capability_request)
        if existing:
            logger.info(f"Found existing tool: {existing.name}")
            existing.usage_count += 1
            self._save_registry()
            return existing

        # 2. Generate tool specification via LLM
        logger.info("Generating tool specification...")
        spec = self._generate_spec(capability_request)
        if not spec:
            logger.error("Failed to generate tool specification")
            return None

        logger.info(f"Building tool: {spec['name']}")

        # 3. Build full tool code from template
        tool_code = self._build_tool_code(spec)

        # 4. Validate by running in subprocess
        logger.info("Validating in sandbox...")
        valid, output = self._validate_code(tool_code)

        # 5. If validation fails, try to fix once
        if not valid:
            logger.warning("Validation failed, attempting fix...")
            logger.warning(f"Validation failed: {output}")
            fixed_code = self._fix_code(tool_code, output)

            if fixed_code != tool_code:
                valid, output = self._validate_code(fixed_code)
                if valid:
                    tool_code = fixed_code
                    logger.info("Fix successful!")

        # 6. Create tool object
        tool = SynthesizedTool(
            name=spec["name"],
            description=spec["description"],
            code=tool_code,
            created_at=datetime.now().isoformat(),
            test_passed=valid,
            usage_count=1
        )

        # 7. Save to disk and registry
        if valid:
            self._save_tool_file(tool)
            self.registry[tool.name] = tool
            self._save_registry()
            logger.info(f"Tool saved: {tool.name}")
        else:
            logger.warning(f"Tool {tool.name} failed validation: {output}")
            logger.warning(f"Tool validation failed: {output[:100]}")

        return tool

    def execute_tool(self, tool_name: str, **kwargs) -> ToolResult:
        """
        Execute a synthesized tool.

        Args:
            tool_name: Name of the tool to execute
            **kwargs: Arguments to pass to the tool

        Returns:
            ToolResult with success status, result data, or error message.
        """
        if tool_name not in self.registry:
            return ToolResult(success=False, error=f"Tool '{tool_name}' not found")

        tool = self.registry[tool_name]

        if not tool.test_passed:
            return ToolResult(success=False, error=f"Tool '{tool_name}' failed validation")

        # Safety check on tool code before execution
        dangerous, reason = _scan_for_dangerous_code(tool.code)
        if dangerous:
            return ToolResult(success=False, error=f"Generated code failed safety check: {reason}")

        # Build execution code
        args_str = ", ".join(f"{k}={repr(v)}" for k, v in kwargs.items())

        exec_code = f'''
{tool.code}

if __name__ == "__main__":
    result = execute({args_str})
    import json
    print("RESULT_JSON:" + json.dumps(result))
'''

        # Run in subprocess
        with tempfile.NamedTemporaryFile(
            mode='w',
            suffix='.py',
            delete=False,
            encoding='utf-8'
        ) as f:
            f.write(exec_code)
            f.flush()
            temp_path = Path(f.name)

        try:
            result = subprocess.run(
                [sys.executable, str(temp_path)],
                capture_output=True,
                text=True,
                timeout=10,
                cwd=tempfile.gettempdir(),
                env=_SAFE_ENV,
            )

            # Extract result from output
            for line in result.stdout.split('\n'):
                if line.startswith("RESULT_JSON:"):
                    json_str = line[len("RESULT_JSON:"):]
                    tool.usage_count += 1
                    self._save_registry()
                    parsed = json.loads(json_str)
                    return ToolResult(
                        success=parsed.get("success", False),
                        result=parsed.get("result"),
                        error=parsed.get("error", ""),
                    )

            if result.returncode != 0:
                return ToolResult(success=False, error=result.stderr)

            return ToolResult(success=False, error="No result returned")

        except subprocess.TimeoutExpired:
            return ToolResult(success=False, error="Execution timed out")
        except json.JSONDecodeError as e:
            return ToolResult(success=False, error=f"Invalid result format: {e}")
        except Exception as e:
            return ToolResult(success=False, error=str(e))
        finally:
            temp_path.unlink(missing_ok=True)

    def list_tools(self) -> List[Dict]:
        """List all synthesized tools."""
        return [
            {
                "name": tool.name,
                "description": tool.description,
                "created": tool.created_at,
                "valid": tool.test_passed,
                "uses": tool.usage_count
            }
            for tool in self.registry.values()
        ]

    def delete_tool(self, tool_name: str) -> bool:
        """Delete a synthesized tool."""
        if tool_name not in self.registry:
            return False

        # Remove file
        tool_path = self.tools_dir / f"{tool_name}.py"
        tool_path.unlink(missing_ok=True)

        # Remove from registry
        del self.registry[tool_name]
        self._save_registry()

        logger.info(f"Deleted tool: {tool_name}")
        return True

    def get_tool_code(self, tool_name: str) -> Optional[str]:
        """Get the source code of a tool."""
        if tool_name in self.registry:
            return self.registry[tool_name].code
        return None


if __name__ == "__main__":
    print("=" * 60)
    print("SynapseForge - Dynamic Tool Creation Test")
    print("=" * 60)

    forge = SynapseForge()

    print(f"\nLoaded {len(forge.registry)} existing tools")

    # Test 1: Create a temperature converter
    print("\n--- Test 1: Creating temperature converter ---")
    tool = forge.synthesize("convert celsius to fahrenheit temperature")

    if tool:
        print(f"Created: {tool.name}")
        print(f"Description: {tool.description}")
        print(f"Validated: {tool.test_passed}")

        if tool.test_passed:
            # Test 2: Use the tool
            print("\n--- Test 2: Using the tool ---")
            result = forge.execute_tool(tool.name, celsius=100)
            print(f"100°C = {result}")

            result = forge.execute_tool(tool.name, celsius=0)
            print(f"0°C = {result}")
    else:
        print("Failed to create tool")

    # Test 3: Create another tool
    print("\n--- Test 3: Creating word counter ---")
    tool2 = forge.synthesize("count the number of words in a text string")

    if tool2 and tool2.test_passed:
        print(f"Created: {tool2.name}")
        result = forge.execute_tool(tool2.name, text="hello world this is a test")
        print(f"Word count result: {result}")

    # Test 4: List all tools
    print("\n--- Test 4: All synthesized tools ---")
    for t in forge.list_tools():
        status = "valid" if t["valid"] else "INVALID"
        print(f"  - {t['name']}: {t['description']} [{status}] (used {t['uses']}x)")

    # Test 5: Find existing tool
    print("\n--- Test 5: Finding existing tool ---")
    existing = forge.find_tool("temperature conversion fahrenheit")
    if existing:
        print(f"Found: {existing.name}")
    else:
        print("No matching tool found")

    print("\n" + "=" * 60)
    print("Test complete!")
    print(f"Total tools in registry: {len(forge.registry)}")
