"""
Proactive Awareness Engine — ADV-02 Phase 3.

Surfaces insights the user hasn't asked about: stale projects,
approaching deadlines, unresolved contradictions, relationship gaps,
and goal-blocker connections.

Runs two modes:
  - Quick analysis: after each conversation (staleness, deadlines, contradictions)
  - Full analysis: during idle time (all 8 checks)

Insights are stored in the proactive_insights table and surfaced
via get_awareness_context() into inner thoughts.
"""

import logging
import threading
import uuid
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import Dict, List, Optional

from aura.config import Config

logger = logging.getLogger(__name__)


# ============================================================================
# Enums & Dataclasses
# ============================================================================

class InsightType(str, Enum):
    STALENESS_ALERT = "staleness_alert"
    BLOCKER_INFERENCE = "blocker_inference"
    PATTERN_ALERT = "pattern_alert"
    PRIORITY_SHIFT = "priority_shift"
    DEADLINE_APPROACHING = "deadline_approaching"
    RELATIONSHIP_GAP = "relationship_gap"
    CONTRADICTION_ALERT = "contradiction_alert"
    STRESS_CORRELATION = "stress_correlation"
    GOAL_RISK = "goal_risk"
    OPPORTUNITY = "opportunity"


@dataclass
class ProactiveInsight:
    """A proactive insight generated by the awareness engine."""
    id: str
    insight_type: InsightType
    title: str
    description: str
    urgency: float = 0.5
    confidence: float = 0.5
    generated_at: str = ""
    delivered_at: Optional[str] = None
    dismissed_at: Optional[str] = None
    acted_on_at: Optional[str] = None
    related_entity_type: Optional[str] = None
    related_entity_id: Optional[str] = None
    reasoning: str = ""

    @property
    def delivery_score(self) -> float:
        """Combined score for delivery priority."""
        return self.urgency * 0.6 + self.confidence * 0.4


# ============================================================================
# Proactive Awareness Engine
# ============================================================================

class ProactiveAwarenessEngine:
    """
    Generates proactive insights by analyzing the world model state.

    Runs checks for staleness, deadlines, contradictions, relationship gaps,
    and goal blockers. Filters, deduplicates, and stores resulting insights.
    """

    MIN_CONFIDENCE = Config.PROACTIVE_MIN_CONFIDENCE
    DELIVERY_URGENCY_THRESHOLD = 0.5
    SIMILAR_INSIGHT_COOLDOWN = 24  # hours
    MAX_INSIGHTS_PER_RUN = 3

    def __init__(self, world_model, enabled: bool = True):
        self._world_model = world_model
        self._enabled = enabled
        self._lock = threading.RLock()
        self._confidence_overrides: Dict[str, float] = {}
        self._last_tune_time: float = 0.0

    # ----------------------------------------------------------------
    # Analysis entry points
    # ----------------------------------------------------------------

    def run_full_analysis(self) -> List[ProactiveInsight]:
        """Run all 8 checks, filter, dedup, store, and return insights."""
        if not self._enabled:
            return []

        self._tune_thresholds()

        all_insights = []
        all_insights.extend(self.check_staleness())
        all_insights.extend(self.check_deadlines())
        all_insights.extend(self.check_contradictions())
        all_insights.extend(self.check_relationship_gaps())
        all_insights.extend(self.check_goal_blockers())
        all_insights.extend(self.check_patterns())
        all_insights.extend(self.check_priority_shifts())
        all_insights.extend(self.check_stress_correlations())

        filtered = self._filter_and_dedup(all_insights)

        for insight in filtered:
            self._store_insight(insight)

        if filtered:
            logger.info(
                f"[ProactiveAwareness] Full analysis generated {len(filtered)} insights"
            )

        return filtered

    def run_quick_analysis(self) -> List[ProactiveInsight]:
        """Run only fast checks (staleness, deadlines, contradictions)."""
        if not self._enabled:
            return []

        all_insights = []
        all_insights.extend(self.check_staleness())
        all_insights.extend(self.check_deadlines())
        all_insights.extend(self.check_contradictions())

        filtered = self._filter_and_dedup(all_insights)

        for insight in filtered:
            self._store_insight(insight)

        if filtered:
            logger.info(
                f"[ProactiveAwareness] Quick analysis generated {len(filtered)} insights"
            )

        return filtered

    # ----------------------------------------------------------------
    # Check methods — real implementations
    # ----------------------------------------------------------------

    def check_staleness(self) -> List[ProactiveInsight]:
        """Check for active projects with no recent activity."""
        insights = []
        try:
            from aura.consciousness.world_model import ProjectStatus
            active = self._world_model.get_projects_by_status(ProjectStatus.ACTIVE)

            for project in active:
                days = self._world_model._days_since(project.last_activity)
                if days is None or days < 7:
                    continue

                # Urgency scales with staleness: 0.5 at 7d, 0.7 at 14d, 0.9 at 30d
                urgency = min(0.9, 0.5 + (days - 7) * 0.02)
                confidence = min(0.9, 0.6 + (days - 7) * 0.01)

                insights.append(ProactiveInsight(
                    id=f"stale_{project.id}_{uuid.uuid4().hex[:6]}",
                    insight_type=InsightType.STALENESS_ALERT,
                    title=f"'{project.name}' has been inactive for {days} days",
                    description=(
                        f"Project '{project.name}' hasn't had any activity in {days} days. "
                        f"Consider checking in or updating its status."
                    ),
                    urgency=urgency,
                    confidence=confidence,
                    generated_at=datetime.now(timezone.utc).isoformat(),
                    related_entity_type="project",
                    related_entity_id=project.id,
                    reasoning=f"last_activity={project.last_activity}, days_stale={days}",
                ))

        except Exception as e:
            logger.debug(f"[ProactiveAwareness] check_staleness error: {e}")

        return insights

    def check_deadlines(self) -> List[ProactiveInsight]:
        """Check for goals with approaching target dates."""
        insights = []
        try:
            active_goals = self._world_model.get_active_goals()

            for goal in active_goals:
                if not goal.target_date:
                    continue

                try:
                    target = datetime.fromisoformat(goal.target_date)
                    if target.tzinfo is None:
                        target = target.replace(tzinfo=timezone.utc)
                except (ValueError, TypeError):
                    continue

                now = datetime.now(timezone.utc)
                days_remaining = (target - now).days

                if days_remaining < 0:
                    # Past deadline
                    urgency = 0.95
                    confidence = 0.9
                    title = f"Goal overdue: '{goal.description}'"
                    desc = (
                        f"Goal '{goal.description}' was due {abs(days_remaining)} days ago "
                        f"and is at {int(goal.progress * 100)}% progress."
                    )
                elif days_remaining <= 7:
                    urgency = 0.8
                    confidence = 0.85
                    title = f"Goal due within a week: '{goal.description}'"
                    desc = (
                        f"Goal '{goal.description}' is due in {days_remaining} days "
                        f"({int(goal.progress * 100)}% complete)."
                    )
                elif days_remaining <= 14:
                    urgency = 0.6
                    confidence = 0.7
                    title = f"Goal approaching: '{goal.description}'"
                    desc = (
                        f"Goal '{goal.description}' is due in {days_remaining} days "
                        f"({int(goal.progress * 100)}% complete)."
                    )
                elif days_remaining <= 30:
                    urgency = 0.4
                    confidence = 0.6
                    title = f"Goal on horizon: '{goal.description}'"
                    desc = (
                        f"Goal '{goal.description}' is due in {days_remaining} days."
                    )
                else:
                    continue

                insights.append(ProactiveInsight(
                    id=f"deadline_{goal.id}_{uuid.uuid4().hex[:6]}",
                    insight_type=InsightType.DEADLINE_APPROACHING,
                    title=title,
                    description=desc,
                    urgency=urgency,
                    confidence=confidence,
                    generated_at=datetime.now(timezone.utc).isoformat(),
                    related_entity_type="goal",
                    related_entity_id=goal.id,
                    reasoning=f"target_date={goal.target_date}, days_remaining={days_remaining}",
                ))

        except Exception as e:
            logger.debug(f"[ProactiveAwareness] check_deadlines error: {e}")

        return insights

    def check_contradictions(self) -> List[ProactiveInsight]:
        """Check for unresolved contradictions older than 24 hours."""
        insights = []
        try:
            unresolved = self._world_model.get_unresolved_contradictions()

            for contradiction in unresolved:
                hours_old = self._hours_since(contradiction.detected_at)
                if hours_old is None or hours_old < 24:
                    continue

                # Urgency builds over time: 0.5 at 24h, 0.7 at 72h, 0.9 at 168h
                urgency = min(0.9, 0.5 + (hours_old - 24) * 0.003)
                confidence = 0.7

                insights.append(ProactiveInsight(
                    id=f"contra_{contradiction.id}_{uuid.uuid4().hex[:6]}",
                    insight_type=InsightType.CONTRADICTION_ALERT,
                    title=f"Unresolved contradiction ({int(hours_old)}h old)",
                    description=(
                        f"Contradiction detected {int(hours_old)} hours ago: "
                        f"{contradiction.description}"
                    ),
                    urgency=urgency,
                    confidence=confidence,
                    generated_at=datetime.now(timezone.utc).isoformat(),
                    related_entity_type="contradiction",
                    related_entity_id=contradiction.id,
                    reasoning=f"detected_at={contradiction.detected_at}, hours_old={hours_old:.1f}",
                ))

        except Exception as e:
            logger.debug(f"[ProactiveAwareness] check_contradictions error: {e}")

        return insights

    def check_relationship_gaps(self) -> List[ProactiveInsight]:
        """Check for important relationships with communication gaps."""
        insights = []
        try:
            important_roles = {
                "manager", "boss", "supervisor", "mentor", "advisor",
                "collaborator", "partner", "co-founder", "team lead",
                "client", "customer",
            }

            for rel in self._world_model._relationships.values():
                # Important if role matches or mention_count >= 3
                role_lower = (rel.role or "").lower()
                is_important = (
                    role_lower in important_roles
                    or rel.mention_count >= 3
                )

                if not is_important:
                    continue

                days_gap = self._world_model._days_since(rel.last_mentioned)
                if days_gap is None or days_gap < 14:
                    continue

                urgency = min(0.8, 0.4 + (days_gap - 14) * 0.01)
                confidence = 0.6

                insights.append(ProactiveInsight(
                    id=f"relgap_{rel.id}_{uuid.uuid4().hex[:6]}",
                    insight_type=InsightType.RELATIONSHIP_GAP,
                    title=f"Haven't mentioned {rel.name} in {days_gap} days",
                    description=(
                        f"{rel.name} ({rel.role or rel.relationship_type}) "
                        f"hasn't been mentioned in {days_gap} days. "
                        f"Previously mentioned {rel.mention_count} times."
                    ),
                    urgency=urgency,
                    confidence=confidence,
                    generated_at=datetime.now(timezone.utc).isoformat(),
                    related_entity_type="relationship",
                    related_entity_id=rel.id,
                    reasoning=f"last_mentioned={rel.last_mentioned}, gap={days_gap}d, mentions={rel.mention_count}",
                ))

        except Exception as e:
            logger.debug(f"[ProactiveAwareness] check_relationship_gaps error: {e}")

        return insights

    def check_goal_blockers(self) -> List[ProactiveInsight]:
        """Check for active goals with related projects that have ongoing blockers."""
        insights = []
        try:
            active_goals = self._world_model.get_active_goals()

            for goal in active_goals:
                if not goal.related_project_ids:
                    continue

                for proj_id in goal.related_project_ids:
                    blockers = self._world_model.get_project_blockers(proj_id)
                    ongoing = [b for b in blockers if b.get("status") == "ongoing"]

                    if not ongoing:
                        continue

                    project = self._world_model.get_project(proj_id)
                    proj_name = project.name if project else proj_id

                    blocker_descs = [b["description"] for b in ongoing[:2]]
                    urgency = min(0.8, 0.5 + len(ongoing) * 0.1)
                    confidence = 0.65

                    insights.append(ProactiveInsight(
                        id=f"goalblocker_{goal.id}_{uuid.uuid4().hex[:6]}",
                        insight_type=InsightType.GOAL_RISK,
                        title=f"Goal at risk: blockers in '{proj_name}'",
                        description=(
                            f"Goal '{goal.description}' may be at risk — "
                            f"project '{proj_name}' has {len(ongoing)} ongoing blocker(s): "
                            f"{'; '.join(blocker_descs)}"
                        ),
                        urgency=urgency,
                        confidence=confidence,
                        generated_at=datetime.now(timezone.utc).isoformat(),
                        related_entity_type="goal",
                        related_entity_id=goal.id,
                        reasoning=f"project={proj_id}, ongoing_blockers={len(ongoing)}",
                    ))

        except Exception as e:
            logger.debug(f"[ProactiveAwareness] check_goal_blockers error: {e}")

        return insights

    # ----------------------------------------------------------------
    # Check methods — Phase 4 implementations
    # ----------------------------------------------------------------

    def check_patterns(self) -> List[ProactiveInsight]:
        """Detect high-confidence recurring patterns across conversations."""
        insights = []
        try:
            from aura.patterns import get_pattern_prophet
            prophet = get_pattern_prophet()

            candidates = []
            for pattern in prophet.patterns.values():
                if pattern.confidence < 0.5 or pattern.occurrences < 3:
                    continue
                # Skip stale patterns (not seen in 14+ days)
                if pattern.last_seen:
                    hours = self._hours_since(pattern.last_seen)
                    if hours is not None and hours > 336:  # 14 days
                        continue
                candidates.append(pattern)

            # Cap at 3 candidates, sorted by confidence descending
            candidates.sort(key=lambda p: p.confidence, reverse=True)
            for pattern in candidates[:3]:
                urgency = min(0.8, 0.4 + pattern.confidence * 0.3)
                insights.append(ProactiveInsight(
                    id=f"pattern_{uuid.uuid4().hex[:8]}",
                    insight_type=InsightType.PATTERN_ALERT,
                    title=f"Recurring pattern: {pattern.name}",
                    description=(
                        f"Pattern '{pattern.name}' detected with "
                        f"{pattern.occurrences} occurrences "
                        f"(confidence: {pattern.confidence:.0%}). "
                        f"{pattern.description or ''}"
                    ),
                    urgency=urgency,
                    confidence=pattern.confidence,
                    generated_at=datetime.now(timezone.utc).isoformat(),
                    related_entity_type="pattern",
                    related_entity_id=pattern.name,
                    reasoning=f"occurrences={pattern.occurrences}, confidence={pattern.confidence:.2f}",
                ))

        except Exception as e:
            logger.debug(f"[ProactiveAwareness] check_patterns error: {e}")

        return insights

    def check_priority_shifts(self) -> List[ProactiveInsight]:
        """Detect implicit priority changes by comparing state_change activity windows."""
        insights = []
        try:
            now = datetime.now(timezone.utc)
            recent_since = (now - timedelta(days=7)).isoformat()
            prior_since = (now - timedelta(days=14)).isoformat()
            prior_until = recent_since

            recent_counts = self._world_model.get_state_change_counts(
                "project", since=recent_since
            )
            prior_counts = self._world_model.get_state_change_counts(
                "project", since=prior_since, until=prior_until
            )

            # Collect all project IDs from both windows
            all_ids = set(recent_counts.keys()) | set(prior_counts.keys())

            for proj_id in all_ids:
                recent = recent_counts.get(proj_id, 0)
                prior = prior_counts.get(proj_id, 0)

                shift_type = None
                if recent >= 5 and prior <= 1:
                    shift_type = "surging"
                    urgency = 0.6
                    confidence = 0.65
                elif prior >= 5 and recent <= 1:
                    shift_type = "dropped off"
                    urgency = 0.7
                    confidence = 0.6
                else:
                    continue

                # Resolve project name
                project = self._world_model.get_project(proj_id)
                proj_name = project.name if project else proj_id

                insights.append(ProactiveInsight(
                    id=f"prishift_{proj_id}_{uuid.uuid4().hex[:6]}",
                    insight_type=InsightType.PRIORITY_SHIFT,
                    title=f"Activity {shift_type} on '{proj_name}'",
                    description=(
                        f"Project '{proj_name}' activity has {shift_type}: "
                        f"{prior} changes in prior week vs {recent} in recent week."
                    ),
                    urgency=urgency,
                    confidence=confidence,
                    generated_at=datetime.now(timezone.utc).isoformat(),
                    related_entity_type="project",
                    related_entity_id=proj_id,
                    reasoning=f"recent_changes={recent}, prior_changes={prior}",
                ))

        except Exception as e:
            logger.debug(f"[ProactiveAwareness] check_priority_shifts error: {e}")

        return insights

    def check_stress_correlations(self) -> List[ProactiveInsight]:
        """Correlate stress signals from ALMA + ToM with workload context."""
        insights = []
        stress_score = 0.0
        stress_sources = []

        # Source 1: ALMA emotional engine
        try:
            from aura.emotion.alma_engine import get_emotional_state
            state = get_emotional_state()
            pad = state.get("pad", {})
            arousal = pad.get("arousal", 0.0)
            pleasure = pad.get("pleasure", 0.0)
            if arousal > 0.5 and pleasure < 0.0:
                alma_stress = (arousal - 0.5) * abs(pleasure)
                stress_score += alma_stress
                stress_sources.append(
                    f"ALMA: high arousal ({arousal:.2f}) + negative valence ({pleasure:.2f})"
                )
        except Exception as e:
            logger.debug(f"[ProactiveAwareness] ALMA stress check error: {e}")

        # Source 2: Theory of Mind
        try:
            from aura.proactive.theory_of_mind import get_theory_of_mind
            tom = get_theory_of_mind()
            emo = tom.get_emotional_state()
            if emo.frustration > 0.5:
                tom_stress = (emo.frustration - 0.5) * 0.5
                stress_score += tom_stress
                stress_sources.append(
                    f"ToM: user frustration ({emo.frustration:.2f})"
                )
        except Exception as e:
            logger.debug(f"[ProactiveAwareness] ToM stress check error: {e}")

        # Only generate insight if combined stress exceeds threshold
        if stress_score < 0.3 or not stress_sources:
            return insights

        # Enrich with workload context
        workload_parts = []
        try:
            from aura.consciousness.world_model import ProjectStatus
            active = self._world_model.get_projects_by_status(ProjectStatus.ACTIVE)
            if active:
                workload_parts.append(f"{len(active)} active project(s)")

            # Count ongoing blockers
            blocker_count = 0
            for proj in active:
                blockers = self._world_model.get_project_blockers(proj.id)
                blocker_count += sum(1 for b in blockers if b.get("status") == "ongoing")
            if blocker_count:
                workload_parts.append(f"{blocker_count} ongoing blocker(s)")

            # Check approaching deadlines
            goals = self._world_model.get_active_goals()
            approaching = 0
            for g in goals:
                if g.target_date:
                    try:
                        target = datetime.fromisoformat(g.target_date)
                        if target.tzinfo is None:
                            target = target.replace(tzinfo=timezone.utc)
                        days_left = (target - datetime.now(timezone.utc)).days
                        if 0 <= days_left <= 7:
                            approaching += 1
                    except (ValueError, TypeError):
                        pass
            if approaching:
                workload_parts.append(f"{approaching} deadline(s) within 7 days")
        except Exception as e:
            logger.debug(f"[ProactiveAwareness] non-critical: {e}")
        workload_context = "; ".join(workload_parts) if workload_parts else "no specific workload data"
        urgency = min(0.9, 0.5 + stress_score)
        confidence = min(0.8, 0.5 + len(stress_sources) * 0.15)

        insights.append(ProactiveInsight(
            id=f"stress_{uuid.uuid4().hex[:8]}",
            insight_type=InsightType.STRESS_CORRELATION,
            title="Stress signals detected with active workload",
            description=(
                f"Stress indicators from {', '.join(stress_sources)}. "
                f"Current workload: {workload_context}."
            ),
            urgency=urgency,
            confidence=confidence,
            generated_at=datetime.now(timezone.utc).isoformat(),
            related_entity_type="global",
            related_entity_id="global",
            reasoning=f"stress_score={stress_score:.2f}, sources={len(stress_sources)}",
        ))

        return insights

    # ----------------------------------------------------------------
    # Threshold Tuning (ADV-02 Phase 5)
    # ----------------------------------------------------------------

    def _tune_thresholds(self) -> None:
        """Adjust per-type confidence thresholds based on engagement rates.

        Rate-limited to once per hour. Types with high engagement get a
        lower threshold (more insights); types with low engagement get a
        higher threshold (less noise).
        """
        import time as _time
        now = _time.monotonic()
        if now - self._last_tune_time < 3600:
            return
        self._last_tune_time = now

        try:
            rates = self._world_model.get_insight_engagement_rates(days=30)
        except Exception:
            return

        for insight_type, data in rates.items():
            if data["total"] < 5:
                continue
            current = self._confidence_overrides.get(insight_type, self.MIN_CONFIDENCE)
            if data["engagement_rate"] > 0.6:
                self._confidence_overrides[insight_type] = max(0.3, current - 0.02)
            elif data["engagement_rate"] < 0.2:
                self._confidence_overrides[insight_type] = min(0.7, current + 0.02)

    # ----------------------------------------------------------------
    # Filtering & Storage
    # ----------------------------------------------------------------

    def _filter_and_dedup(
        self, insights: List[ProactiveInsight]
    ) -> List[ProactiveInsight]:
        """
        Filter and deduplicate insights:
        1. Drop below MIN_CONFIDENCE
        2. Dedup by (type, entity_id) within cooldown window
        3. Sort by delivery_score descending
        4. Cap at MAX_INSIGHTS_PER_RUN
        """
        # Step 1: confidence filter (per-type overrides from _tune_thresholds)
        filtered = [
            i for i in insights
            if i.confidence >= self._confidence_overrides.get(
                i.insight_type.value, self.MIN_CONFIDENCE
            )
        ]

        # Step 2: dedup against recent insights in DB
        deduped = []
        for insight in filtered:
            recent = self._world_model.get_recent_insights(
                insight_type=insight.insight_type.value,
                hours=self.SIMILAR_INSIGHT_COOLDOWN,
            )

            # Check if same entity already has a recent insight of this type
            already_exists = any(
                r.get("related_entity_id") == insight.related_entity_id
                for r in recent
            )

            if not already_exists:
                deduped.append(insight)

        # Step 3: sort by delivery_score
        deduped.sort(key=lambda i: i.delivery_score, reverse=True)

        # Step 4: cap
        return deduped[: self.MAX_INSIGHTS_PER_RUN]

    def _store_insight(self, insight: ProactiveInsight) -> None:
        """Delegate storage to world model."""
        self._world_model.store_insight(insight)

    # ----------------------------------------------------------------
    # Retrieval & Feedback
    # ----------------------------------------------------------------

    def get_pending_insights(self, max_count: int = 3) -> List[Dict]:
        """Get pending insights above the delivery urgency threshold."""
        pending = self._world_model.get_pending_insights(max_count=max_count)
        return [
            p for p in pending
            if p.get("urgency", 0) >= self.DELIVERY_URGENCY_THRESHOLD
        ]

    def record_insight_feedback(self, insight_id: str, feedback: str) -> bool:
        """
        Record user feedback on an insight.
        'engaged' -> sets acted_on_at
        'dismissed' -> sets dismissed_at
        """
        if feedback == "engaged":
            return self._world_model.update_insight_feedback(insight_id, "engaged")
        elif feedback == "dismissed":
            return self._world_model.update_insight_feedback(insight_id, "dismissed")
        return False

    # ----------------------------------------------------------------
    # Context methods
    # ----------------------------------------------------------------

    def get_awareness_context(self) -> str:
        """
        Build a [Proactive Awareness] text block for inner thoughts.
        Shows top 2 pending insights + gap/staleness counts.
        """
        if not self._enabled:
            return ""

        parts = []

        try:
            pending = self.get_pending_insights(max_count=2)
            if pending:
                for p in pending:
                    parts.append(
                        f"- {p['title']} (urgency: {p['urgency']:.1f})"
                    )
        except Exception as e:
            logger.debug(f"[ProactiveAwareness] non-critical: {e}")
        # Add summary counts
        try:
            from aura.consciousness.world_model import ProjectStatus
            active = self._world_model.get_projects_by_status(ProjectStatus.ACTIVE)
            stale_count = sum(
                1 for p in active
                if (self._world_model._days_since(p.last_activity) or 0) >= 7
            )
            if stale_count:
                parts.append(f"- {stale_count} stale project(s)")

            unresolved = self._world_model.get_unresolved_contradictions()
            if unresolved:
                parts.append(f"- {len(unresolved)} unresolved contradiction(s)")

        except Exception as e:

            logger.debug(f"[ProactiveAwareness] non-critical: {e}")
        if not parts:
            return ""

        return "[Proactive Awareness]\n" + "\n".join(parts)

    def get_drive_signals(self) -> Dict[str, float]:
        """
        Compute drive signals for Phase 4 IntrinsicMotivation wiring.

        Returns {curiosity, coherence, social, competence} floats 0-1.
        """
        signals = {
            "curiosity": 0.5,
            "coherence": 0.5,
            "social": 0.5,
            "competence": 0.5,
        }

        try:
            # Contradictions reduce coherence drive
            unresolved = self._world_model.get_unresolved_contradictions()
            if unresolved:
                signals["coherence"] = max(0.1, 0.5 - len(unresolved) * 0.1)

            # Relationship gaps increase social drive
            gap_count = 0
            for rel in self._world_model._relationships.values():
                days = self._world_model._days_since(rel.last_mentioned)
                if days is not None and days >= 14 and rel.mention_count >= 3:
                    gap_count += 1
            if gap_count:
                signals["social"] = min(0.9, 0.5 + gap_count * 0.1)

            # Stale projects increase curiosity
            from aura.consciousness.world_model import ProjectStatus
            active = self._world_model.get_projects_by_status(ProjectStatus.ACTIVE)
            stale = sum(
                1 for p in active
                if (self._world_model._days_since(p.last_activity) or 0) >= 7
            )
            if stale:
                signals["curiosity"] = min(0.9, 0.5 + stale * 0.1)

            # Goal blockers reduce competence
            goals = self._world_model.get_active_goals()
            blocked = 0
            for g in goals:
                for pid in (g.related_project_ids or []):
                    blockers = self._world_model.get_project_blockers(pid)
                    if any(b.get("status") == "ongoing" for b in blockers):
                        blocked += 1
                        break
            if blocked:
                signals["competence"] = max(0.1, 0.5 - blocked * 0.1)

        except Exception as e:
            logger.debug(f"[ProactiveAwareness] get_drive_signals error: {e}")

        return signals

    # ----------------------------------------------------------------
    # Helpers
    # ----------------------------------------------------------------

    def _hours_since(self, iso_str: str) -> Optional[float]:
        """Compute hours since an ISO timestamp."""
        if not iso_str:
            return None
        try:
            dt = datetime.fromisoformat(iso_str)
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            delta = datetime.now(timezone.utc) - dt
            return max(0.0, delta.total_seconds() / 3600)
        except (ValueError, TypeError):
            return None


# ============================================================================
# Singleton
# ============================================================================

_engine: Optional[ProactiveAwarenessEngine] = None
_engine_lock = threading.Lock()


def get_proactive_awareness_engine() -> ProactiveAwarenessEngine:
    """Get or create the singleton ProactiveAwarenessEngine (double-checked locking)."""
    global _engine
    if _engine is None:
        with _engine_lock:
            if _engine is None:
                from aura.consciousness.world_model import get_world_model
                from aura.config import Config
                _engine = ProactiveAwarenessEngine(
                    world_model=get_world_model(),
                    enabled=getattr(Config, "PROACTIVE_AWARENESS_ENABLED", True),
                )
    return _engine
