package com.aura.proactive

import android.content.Context
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.stringPreferencesKey
import androidx.datastore.preferences.preferencesDataStore
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.flow.first
import javax.inject.Inject
import javax.inject.Singleton

private val Context.proactiveMessageStore by preferencesDataStore("proactive_messages")

/**
 * Stores a single proactive in-chat message generated by AgentPresence.
 *
 * When the user opens the app after a gap, ChatRoute calls [consumeMessage].
 * If a message is waiting (set by DaemonWorker), it appears as an
 * assistant chat bubble with a "proactive" badge. The user can tap
 * "Let's talk" to start a real conversation, or dismiss it.
 *
 * The store holds only the latest message — older ones are overwritten.
 * Messages are one-shot: once consumed, they're cleared.
 */
@Singleton
class ProactiveMessageStore @Inject constructor(
    @ApplicationContext private val context: Context,
) {
    companion object {
        private val KEY_MESSAGE = stringPreferencesKey("proactive_message")
        private val KEY_TIMESTAMP = stringPreferencesKey("proactive_timestamp")
    }

    suspend fun setMessage(text: String) {
        context.proactiveMessageStore.edit { prefs ->
            prefs[KEY_MESSAGE] = text
            prefs[KEY_TIMESTAMP] = System.currentTimeMillis().toString()
        }
    }

    suspend fun consumeMessage(): String? {
        val prefs = context.proactiveMessageStore.data.first()
        val message = prefs[KEY_MESSAGE] ?: return null
        // Clear after reading — one-shot.
        context.proactiveMessageStore.edit { it.remove(KEY_MESSAGE); it.remove(KEY_TIMESTAMP) }
        return message
    }

    suspend fun clear() {
        context.proactiveMessageStore.edit { it.remove(KEY_MESSAGE); it.remove(KEY_TIMESTAMP) }
    }
}