#!/usr/bin/env python3
"""Regenerate the expected token ids for WordPieceTokenizerTest.

    pip install transformers
    python scripts/gen_tokenizer_fixture.py

Why a fixture rather than hand-written expectations: a WordPiece implementation that is
subtly wrong does not fail loudly. It returns a well-formed sequence, the model returns a
well-formed vector of the right length, and nothing errors — the embedding is simply of
text the model was never shown. Recall gets worse for a reason no log explains.

Writing the expectations by hand would encode my understanding of BERT tokenization, which
is the thing under test. These come from the reference tokenizer, so the test compares the
implementation against the thing it has to match instead of against my belief about it.

The emoji case is in here for a reason. The first implementation deleted emoji entirely —
Kotlin stores them as surrogate pairs, Character.getType calls each half a SURROGATE, and
a Char-wise loop classified them as control characters. The reference keeps them and lets
WordPiece resolve them to [UNK]. Nothing else in the suite would have caught it.

Rerun this after changing MODEL, and commit the result in the same change.
"""
import io
import json
import sys

MODEL = "nomic-ai/nomic-embed-text-v1.5"
OUT = "aura-core/src/test/resources/tokenizer/nomic_wordpiece.jsonl"

CASES = [
    "hello world",
    "Elnur prefers concise answers with no preamble",
    "The Aura Android project lives at D drive aura-android-clean",
    "don't split contractions wrongly",
    "unbelievably tokenizationalism",
    "CamelCase and UPPERCASE and lower",
    "numbers 12345 and 3.14 and 2026-08-20",
    "punctuation!!! really? yes; indeed.",
    "  leading and trailing whitespace  ",
    "emoji \U0001F600 and unicode café naïve",
    "a",
    "",
    "schema forward in place rather than dual-write during the cutover",
    "search_query: how did we decide to handle the database change",
]

HEADER = (
    "// Expected token ids from HuggingFace BertTokenizer for " + MODEL + ".\n"
    "// Generated by scripts/gen_tokenizer_fixture.py. A Kotlin tokenizer that does not\n"
    "// reproduce these exactly produces embeddings from different text than the model\n"
    "// was trained on, and fails silently by returning plausible-looking vectors.\n"
)


def main() -> int:
    try:
        from transformers import AutoTokenizer
    except ImportError:
        print("pip install transformers", file=sys.stderr)
        return 1

    tok = AutoTokenizer.from_pretrained(MODEL)
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER)
        for case in CASES:
            ids = tok(case, add_special_tokens=True)["input_ids"]
            f.write(json.dumps({"text": case, "ids": ids}, ensure_ascii=False) + "\n")
    print(f"{len(CASES)} cases -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
