package com.aura.memory.onnx

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * The tokenizer must reproduce HuggingFace exactly, or the model reads different text.
 *
 * This is the failure mode that does not announce itself. A tokenizer that is subtly wrong
 * — splits a contraction differently, mishandles an accent, drops a special token — still
 * returns a perfectly well-formed vector of the right length. Nothing errors. The
 * embeddings are simply of text the model was never given, and recall quietly gets worse
 * for reasons no log explains.
 *
 * So the expectations are not hand-written. They are the real `BertTokenizer`'s output for
 * `nomic-ai/nomic-embed-text-v1.5`, generated by `scripts/gen_tokenizer_fixture.py` and
 * committed. Equality with those ids is the whole contract.
 */
class WordPieceTokenizerTest {

    private val cases: List<Pair<String, List<Int>>> by lazy {
        val text = javaClass.getResourceAsStream("/tokenizer/nomic_wordpiece.jsonl")
            ?.bufferedReader()?.readText()
            ?: error(
                "Missing /tokenizer/nomic_wordpiece.jsonl. This must FAIL rather than skip: a " +
                    "tokenizer test with no expectations passes while proving nothing.",
            )
        text.lineSequence()
            .filter { it.isNotBlank() && !it.startsWith("//") }
            .map { line ->
                val obj = Json.parseToJsonElement(line).jsonObject
                obj["text"]!!.jsonPrimitive.content to
                    obj["ids"]!!.jsonArray.map { it.jsonPrimitive.content.toInt() }
            }
            .toList()
    }

    /**
     * Read from the assets directory on disk rather than the classpath.
     *
     * Android assets are packaged for the device and are not on the JVM test classpath, and
     * committing a second 230 KB copy under test resources would be two files free to drift
     * apart — with the drift invisible, because each would pass its own tests.
     */
    private val tokenizer: WordPieceTokenizer by lazy {
        val cwd = System.getProperty("user.dir")
        val candidates = listOf(
            java.io.File(cwd, "src/main/assets/nomic_vocab.txt"),
            java.io.File(cwd, "aura-core/src/main/assets/nomic_vocab.txt"),
        )
        val file = candidates.firstOrNull { it.isFile }
            ?: error("nomic_vocab.txt not found from cwd=$cwd; tried " + candidates.joinToString())
        WordPieceTokenizer(file.readLines())
    }

    @Test
    fun `the vocabulary is the one the model was trained with`() {
        assertEquals(30522, tokenizer.vocabSize, "wrong vocabulary size for a BERT-base model")
        assertEquals(101, tokenizer.clsId)
        assertEquals(102, tokenizer.sepId)
        assertEquals(0, tokenizer.padId)
    }

    @Test
    fun `every fixture case tokenizes exactly as HuggingFace does`() {
        assertTrue(cases.size >= 10, "only ${cases.size} fixture cases — too few to trust")
        val wrong = cases.mapNotNull { (text, expected) ->
            val actual = tokenizer.encode(text)
            if (actual == expected) null else "  [${text.take(40)}]\n    expected $expected\n    actual   $actual"
        }
        assertTrue(wrong.isEmpty(), "${wrong.size} case(s) disagree with HuggingFace:\n" + wrong.joinToString("\n"))
    }

    @Test
    fun `an unknown word becomes subwords, never a single unknown token`() {
        // WordPiece's entire purpose. Falling back to [UNK] for anything not in the
        // vocabulary would throw away most of the meaning of a rare word, and rare words
        // are exactly what distinguishes one memory from another.
        val ids = tokenizer.encode("unbelievably tokenizationalism")

        assertTrue(ids.size > 4, "expected subword splitting, got $ids")
        assertTrue(tokenizer.unkId !in ids, "fell back to [UNK] instead of splitting: $ids")
    }

    @Test
    fun `input longer than the window is truncated, not dropped`() {
        // A memory longer than the model's window must still embed. Returning nothing, or
        // throwing, would make long memories silently unretrievable.
        val long = List(5_000) { "word$it" }.joinToString(" ")

        val ids = tokenizer.encode(long, maxTokens = 512)

        assertEquals(512, ids.size)
        assertEquals(tokenizer.clsId, ids.first(), "truncation must keep the opening marker")
        assertEquals(tokenizer.sepId, ids.last(), "truncation must keep the closing marker")
    }

    @Test
    fun `empty text still produces the two markers`() {
        assertEquals(listOf(tokenizer.clsId, tokenizer.sepId), tokenizer.encode(""))
    }
}
