package com.aura.world

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * A temporal belief about the user or their world. Beliefs are
 * source-aware, time-bounded, and supersede-able. Unlike memories
 * (which are raw recall items), beliefs are resolved assertions with
 * confidence, validity windows, and evidence chains.
 *
 * When a new belief contradicts an existing one, the old belief is
 * superseded (not deleted) — its supersededBy field points to the
 * replacement. This preserves full history.
 */
@Entity(
    tableName = "beliefs",
    indices = [
        Index(value = ["subject"]),
        Index(value = ["predicate"]),
        Index(value = ["status"]),
        Index(value = ["validFrom"]),
        Index(value = ["confidence"]),
    ],
)
data class BeliefEntity(
    @PrimaryKey val id: kotlin.String,
    /** What the belief is about: "user", "contact", "device", "world". */
    val subject: kotlin.String,
    /** What it says: "name", "location", "preference", "skill", "relationship". */
    val predicate: kotlin.String,
    /** JSON value: string, number, array, or object. */
    val valueJson: kotlin.String,
    val confidence: Float = 1.0f,
    /** Epoch ms. 0 = no start bound. */
    val validFrom: kotlin.Long = 0L,
    /** Epoch ms. 0 = no end bound (still current). */
    val validTo: kotlin.Long = 0L,
    /** "active", "superseded", "expired", "retired". */
    val status: kotlin.String = "active",
    /** ID of the belief that replaced this one, if superseded. */
    val supersededBy: kotlin.String? = null,
    /** Privacy class: "public", "personal", "sensitive". */
    val privacyClass: kotlin.String = "personal",
    val createdAt: kotlin.Long = System.currentTimeMillis(),
    val updatedAt: kotlin.Long = createdAt,
    val lastVerifiedAt: kotlin.Long = 0L,
)

/**
 * Evidence supporting a [BeliefEntity]. A belief may have multiple
 * evidence entries from different sources and times.
 */
@Entity(
    tableName = "evidence",
    indices = [
        Index(value = ["beliefId"]),
        Index(value = ["source"]),
    ],
    foreignKeys = [
        androidx.room.ForeignKey(
            entity = BeliefEntity::class,
            parentColumns = ["id"],
            childColumns = ["beliefId"],
            onDelete = androidx.room.ForeignKey.CASCADE,
        ),
    ],
)
data class EvidenceEntity(
    @PrimaryKey val id: kotlin.String,
    val beliefId: kotlin.String,
    /** "user_statement", "tool_result", "calendar", "notification", "ground_summary", "derived". */
    val source: kotlin.String,
    /** Human-readable summary of the evidence. */
    val summary: kotlin.String,
    /** JSON: raw redacted data for audit (no secrets). */
    val detailJson: kotlin.String = "{}",
    val timestamp: kotlin.Long = System.currentTimeMillis(),
    val confidence: Float = 1.0f,
)

/**
 * A world event observed by the system. Events are append-only and
 * feed the opportunity engine.
 */
@Entity(
    tableName = "world_events",
    indices = [
        Index(value = ["timestamp"]),
        Index(value = ["source"]),
        Index(value = ["eventType"]),
    ],
)
data class WorldEventEntity(
    @PrimaryKey val id: kotlin.String,
    val eventType: kotlin.String,
    val source: kotlin.String,
    val summary: kotlin.String,
    /** JSON: structured redacted payload. */
    val payloadJson: kotlin.String = "{}",
    val timestamp: kotlin.Long = System.currentTimeMillis(),
    /** Whether this event has been consumed by the opportunity engine. */
    val consumed: kotlin.Boolean = false,
)

/**
 * A proposed action generated by the opportunity engine. Proposals
 * are suggestions — the user approves or dismisses them.
 */
@Entity(
    tableName = "opportunities",
    indices = [
        Index(value = ["status"]),
        Index(value = ["benefit"]),
        Index(value = ["urgency"]),
    ],
)
data class OpportunityEntity(
    @PrimaryKey val id: kotlin.String,
    val title: kotlin.String,
    val description: kotlin.String,
    /** "info", "suggestion", "reminder", "action_required". */
    val kind: kotlin.String = "suggestion",
    /** 0.0-1.0 — how beneficial this action would be. */
    val benefit: Float = 0.5f,
    /** 0.0-1.0 — how time-sensitive this is. */
    val urgency: Float = 0.5f,
    /** 0.0-1.0 — confidence in the benefit assessment. */
    val confidence: Float = 0.5f,
    /** JSON: estimated cost/risk class. */
    val costEstimateJson: kotlin.String = "{}",
    /** JSON: evidence (world event IDs, belief IDs supporting this). */
    val evidenceJson: kotlin.String = "[]",
    /** JSON: suggested workflow or tool call to execute. */
    val suggestedActionJson: kotlin.String = "{}",
    /** "proposed", "approved", "dismissed", "executed", "snoozed". */
    val status: kotlin.String = "proposed",
    val createdAt: kotlin.Long = System.currentTimeMillis(),
    val resolvedAt: kotlin.Long? = null,
    /** When to re-surface if snoozed. 0 = no re-surface. */
    val snoozeUntil: kotlin.Long = 0L,
)